#!/bin/bash
TARGET="/web/backend"
GIT_DIR="/home/git/backend.git"
BRANCH="master"

while read oldrev newrev ref
do
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH

                cd $TARGET
                docker-compose up -d --build backend
                yes | docker system prune

                echo "Successfully deployed backend!"
        else                                                                                                     
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done
