# Generated by Django 3.2.6 on 2021-08-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='/imgs/clubs/club_placeholder.jpg', upload_to='imgs/clubs/')),
                ('name', models.CharField(max_length=250)),
                ('mail', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[['cultural', 'CULTURAL'], ['technical', 'TECHNICAL'], ['other', 'OTHER']], default='other', max_length=50)),
                ('state', models.CharField(choices=[['active', 'ACTIVE'], ['deleted', 'DELETED']], default='active', max_length=50)),
            ],
        ),
    ]
