# Generated by Django 3.2.16 on 2022-12-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='imgs/clubs/club_placeholder.jpg', upload_to='imgs/clubs/')),
                ('name', models.CharField(max_length=250)),
                ('mail', models.EmailField(max_length=254)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[['cultural', 'CULTURAL'], ['technical', 'TECHNICAL'], ['other', 'OTHER']], default='other', max_length=50)),
                ('state', models.CharField(choices=[['active', 'ACTIVE'], ['deleted', 'DELETED']], default='active', max_length=50)),
                ('tagline', models.CharField(blank=True, default='No tagline set.', max_length=500, null=True)),
                ('description', models.TextField(default='[{"type":"paragraph", "children":[{"text":""}]}]')),
                ('instagram', models.CharField(blank=True, max_length=700, null=True)),
                ('facebook', models.CharField(blank=True, max_length=700, null=True)),
                ('youtube', models.CharField(blank=True, max_length=700, null=True)),
                ('twitter', models.CharField(blank=True, max_length=700, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=700, null=True)),
                ('discord', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
    ]
