# Generated by Django 3.2.6 on 2021-08-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0002_auto_20210809_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='club',
            name='tagline',
            field=models.CharField(default='No tagline set.', max_length=500),
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[['cultural', 'cultural'], ['technical', 'technical'], ['other', 'other']], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='img',
            field=models.ImageField(default='imgs/clubs/club_placeholder.jpg', upload_to='imgs/clubs/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='state',
            field=models.CharField(choices=[['active', 'active'], ['deleted', 'deleted']], default='active', max_length=50),
        ),
    ]
