# Generated by Django 3.2.6 on 2022-01-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0003_auto_20210822_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[['cultural', 'CULTURAL'], ['technical', 'TECHNICAL'], ['other', 'OTHER']], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='state',
            field=models.CharField(choices=[['active', 'ACTIVE'], ['deleted', 'DELETED']], default='active', max_length=50),
        ),
    ]
