# Generated by Django 3.2.6 on 2022-09-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0004_auto_20220130_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(default='[{"type":"paragraph", "children":[{"text":"No description provided."}]}]'),
        ),
    ]
