# Generated by Django 3.2.6 on 2022-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0005_alter_club_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='tagline',
            field=models.CharField(blank=True, default='No tagline set.', max_length=500, null=True),
        ),
    ]
