# Generated by Django 3.2.6 on 2022-10-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_manager', '0006_alter_club_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='discord',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='facebook',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='linkedin',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='twitter',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='youtube',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
