# Generated by Django 3.2.16 on 2022-12-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('reimbursable', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.event')),
            ],
        ),
    ]
