# Generated by Django 3.2.6 on 2022-03-24 00:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_manager', '0004_auto_20220130_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='imgs/users/')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('mail', models.EmailField(max_length=254)),
                ('batch', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2022, validators=[django.core.validators.MaxValueValidator(3000), django.core.validators.MinValueValidator(2000)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_manager.user')),
            ],
        ),
    ]
