# Generated by Django 3.0.7 on 2021-07-21 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_auto_20210131_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
    ]
