# Generated by Django 3.2.6 on 2022-01-30 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_manager', '0004_auto_20220130_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='imgs/events/')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='No description available.')),
                ('venue', models.TextField(default='-')),
                ('audience', models.TextField(default='none')),
                ('state', models.CharField(choices=[['created', 'CREATED'], ['approved', 'APPROVED'], ['published', 'PUBLISHED'], ['scheduled', 'SCHEDULED'], ['completed', 'COMPLETED'], ['deleted', 'DELETED']], default='created', max_length=50)),
                ('last_edited_by', models.CharField(max_length=250)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.club')),
            ],
        ),
    ]
