# Generated by Django 3.2.16 on 2022-12-05 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_manager', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='No description available.')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='imgs/events/')),
                ('audience', models.TextField(default='none')),
                ('datetimeStart', models.DateTimeField()),
                ('datetimeEnd', models.DateTimeField()),
                ('state', models.IntegerField(choices=[[0, 'incomplete'], [1, 'cc_pending'], [2, 'room|budget_pending'], [3, 'approved'], [4, 'completed'], [5, 'deleted']], default=0)),
                ('room_approved', models.BooleanField(default=False)),
                ('budget_approved', models.BooleanField(default=False)),
                ('room_id', models.IntegerField(choices=[[0, 'none'], [1, 'himalaya_101'], [2, 'himalaya_102'], [3, 'himalaya_103'], [4, 'himalaya_104'], [5, 'himalaya_201'], [6, 'himalaya_202'], [7, 'himalaya_203'], [8, 'himalaya_204'], [9, 'himalaya_301'], [10, 'himalaya_302'], [11, 'himalaya_303'], [12, 'himalaya_304'], [13, 'vindhya_a3_117'], [14, 'vindhya_sh1'], [15, 'vindhya_sh2'], [16, 'amphitheatre'], [17, 'cie_gaming'], [18, 'saranga_hall'], [19, 'himalaya_105'], [20, 'himalaya_205'], [21, 'krb_auditorium'], [22, 'sm24'], [23, 'sm22'], [24, 'sm34'], [25, 'sm32'], [26, 'other']], default=0)),
                ('population', models.IntegerField(default=0)),
                ('equipment', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('additional', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('poc_name', models.CharField(default='', max_length=250)),
                ('poc_email', models.EmailField(default='', max_length=254)),
                ('poc_rollno', models.CharField(default='', max_length=11)),
                ('poc_mobile', models.CharField(default='', max_length=15)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_manager.club')),
            ],
        ),
        migrations.CreateModel(
            name='EventDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
