# Generated by Django 3.2.6 on 2022-05-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='financialRequirements',
        ),
        migrations.AddField(
            model_name='event',
            name='mode',
            field=models.CharField(choices=[['offline', 'Offline'], ['online', 'Online']], default='offline', max_length=50),
        ),
    ]
