# Generated by Django 3.2.6 on 2022-07-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0002_auto_20220510_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='lastEditedBy',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
    ]
