# Generated by Django 3.2.6 on 2022-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0005_auto_20220702_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='state',
        ),
        migrations.AddField(
            model_name='event',
            name='stateKey',
            field=models.IntegerField(choices=[[0, 'cc_pending'], [1, 'fc_pending'], [2, 'gad_pending'], [3, 'fc-gad_pending'], [4, 'slc_pending'], [5, 'slo_pending'], [6, 'approved'], [7, 'completed'], [8, 'deleted']], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='stateRemarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EventState',
        ),
    ]
