# Generated by Django 3.2.6 on 2022-07-09 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_manager', '0006_auto_20220702_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='stateKey',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stateRemarks',
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.IntegerField(choices=[[0, 'cc_pending'], [1, 'fc_pending'], [2, 'gad_pending'], [3, 'slo_pending'], [4, 'slc_pending'], [5, 'approved'], [6, 'completed'], [7, 'deleted']], default=0),
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('message', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_manager.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
