# Generated by Django 3.2.6 on 2022-07-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0008_alter_eventfeedback_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfeedback',
            old_name='user',
            new_name='from_user',
        ),
    ]
