# Generated by Django 3.2.6 on 2022-07-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0009_rename_user_eventfeedback_from_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventfeedback',
            old_name='from_user',
            new_name='user',
        ),
    ]
