# Generated by Django 3.2.6 on 2022-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0010_rename_from_user_eventfeedback_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.IntegerField(choices=[[0, 'cc_pending'], [1, 'fc_pending'], [2, 'gad_pending'], [3, 'fc-gad_pending'], [4, 'slo_pending'], [5, 'slc_pending'], [6, 'approved'], [7, 'completed'], [8, 'deleted']], default=0),
        ),
    ]
