# Generated by Django 3.2.6 on 2022-07-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0011_alter_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='equipment',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='roomId',
            field=models.IntegerField(choices=[[0, 'none'], [1, 'Himalaya_101'], [2, 'Himalaya_102'], [3, 'Himalaya_103'], [4, 'Himalaya_104'], [5, 'Himalaya_105'], [6, 'Vindhya_sh1'], [7, 'Vindhya_sh2'], [8, 'Amphitheatre']], default=0),
        ),
    ]
