# Generated by Django 3.2.6 on 2022-07-26 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0013_remove_event_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='roomId',
            new_name='room_id',
        ),
    ]
