# Generated by Django 3.2.6 on 2022-08-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0015_rename_eventfeedback_eventdiscussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room_id',
            field=models.IntegerField(choices=[[0, 'none'], [1, 'Himalaya_101'], [2, 'Himalaya_102'], [3, 'Himalaya_103'], [4, 'Himalaya_104'], [5, 'Himalaya_201'], [6, 'Himalaya_202'], [7, 'Himalaya_203'], [8, 'Himalaya_204'], [9, 'Himalaya_301'], [10, 'Himalaya_302'], [11, 'Himalaya_303'], [12, 'Himalaya_304'], [13, 'Vindhya A3 117 Conference Room'], [14, 'SH1'], [15, 'SH2'], [16, 'Amphitheatre'], [17, 'CIE Gaming Room'], [18, '*Himalaya_105'], [19, '*Himalaya_205'], [20, '*KRB Auditorium'], [21, '*LTRC Small Meeting Room'], [22, '*KRB Faculty Meeting Room'], [23, 'OTHER (Mention in Additional Requirements Field)']], default=0),
        ),
    ]
