# Generated by Django 3.2.6 on 2022-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0016_alter_event_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='room_id',
            field=models.IntegerField(choices=[[0, 'none'], [1, 'himalaya_101'], [2, 'himalaya_102'], [3, 'himalaya_103'], [4, 'himalaya_104'], [5, 'himalaya_201'], [6, 'himalaya_202'], [7, 'himalaya_203'], [8, 'himalaya_204'], [9, 'himalaya_301'], [10, 'himalaya_302'], [11, 'himalaya_303'], [12, 'himalaya_304'], [13, 'vindhya_a3_117'], [14, 'vindhya_sh1'], [15, 'vindhya_sh2'], [16, 'amphitheatre'], [17, 'cie_gaming'], [18, 'himalaya_105'], [19, 'himalaya_205'], [20, 'krb_auditorium'], [21, 'ltrc_small_mr'], [22, 'krb_faculty_mr'], [23, 'other']], default=0),
        ),
    ]
