# Generated by Django 3.2.6 on 2022-10-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manager', '0018_alter_event_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='[{"type":"paragraph", "children":[{"text":"No description provided."}]}]'),
        ),
    ]
